spring:
  config:
    activate:
      on-profile: prod

  servlet:
    multipart:
      max-file-size: 50B
      max-request-size: 50MB

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver # Postgresql 드라이버 클래스

  data:
    redis:
      url: ${REDISS_URL}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - read:user
              - user:email # 🌟 이 권한이 있어야 비공개 이메일 주소 전용 API에 접근할 수 있습니다.

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ${S3_REGION}
    s3:
      bucket: uploads
      # Supabase S3 등 호환 API 사용 시 엔드포인트 수동 지정 (AWS S3 기본 사용 시 생략 가능)
      endpoint: ${S3_ENDPOINT}

#*production profile sql logging configs
app:
  sql-logging:
    enabled: true
    log-sql: false
    multiline: false
    slow-query-threshold-ms: 2000

logging:
  level:
    org.springframework.security: WARN
    com.kevinj.potfolio.common.logging.sql: WARN
    com.kevinj.potfolio.common.logging.jooq-inline: OFF

jwt:
  secret: ${JWT_SECRET}
  access-ttl-seconds: 900       #15분
  refresh-ttl-seconds: 1209600  #14일
