spring:
  config:
    activate:
      on-profile: dev

  servlet:
    multipart:
      max-file-size: 500B
      max-request-size: 500MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - read:user
              - user:email # 🌟 이 권한이 있어야 비공개 이메일 주소 전용 API에 접근할 수 있습니다.

  datasource:
    url: jdbc:postgresql://my-postgres:5432/devdb
    username: kevinj
    password: 12345^
    driver-class-name: org.postgresql.Driver # Postgresql 드라이버 클래스

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: issuetrack
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: my-redis
      port: 6379

storage:
  local:
    upload-dir: /app/uploads # 실행 위치 기준 로컬 폴더
    base-url: http://localhost:8080/files/

app:
  sql-logging:
    enabled: true
    log-sql: true
    multiline: true
    slow-query-threshold-ms: 1500

logging:
  file:
    path: /app/logs
  level:
    org.springframework.security: WARN
    com.kevinj.potfolio.common.logging.sql: DEBUG
    com.kevinj.potfolio.common.logging.jooq-inline: OFF

jwt:
  secret: 'jeSmI7RZr8KDzGSxWHPnKmvEo4zZAQdqwFGRUPJM8XN'
  access-ttl-seconds: 900       #15분
  refresh-ttl-seconds: 1209600  #14일
